task_indices:
  default: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11,]
class_num:
  default: 12
benchmark_type:
  default: 'ml1'
encoder_type:
  default: 'lstm'
task_name:
  default: 'reach-v2'
title:
  default: 'Reach-v2'
sequence_length:
  default: 20
encoder_size:
  default: 32
point_num:
  default: 200
save_dir:
  default: './picture_lstm_negt'
encoder_path:
  default: "/home/iwbyyyy/ubuntu/paper_code/log/encoder_learning/ml1/reach-v2/seed0/lstm/negt/encoder_lstm_negt.pt"
