task_indices: 
  default: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11,]
loss_type:
  #{'cont': 'contrastive loss', 'negtive power contrastive loss':negt}
  default: 'negt' 
encoder_type:
  # support: {lstm:'lstm', transformer:'transformer', transformer for rl:'transformer_rl'}
  default: 'lstm'
contrasitive_m:
  default: 1
beta:
  default: 0.1
sequence_length:
  default: 20
encoder_size:
  default: 32
benchmark_type:
  default: 'ml1'
task_name:
  default: 'reach-v2'
train_data_ratio:
  default: 0.95
learning_rate:
  default: 3e-4
max_steps:
  default: 10000
batch_size:
  default: 128
eval_interval:
  default: 2
require_improvement:
  default: 1000
save_path:
  default: None
